services:
  whoami:
    container_name: ${NAME}
    image: containous/whoami
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.${NAME}.rule=Host(`${URL}`)
      - traefik.http.routers.${NAME}.middlewares=oauth
networks:
  traefik:
    external: true
x-dockge:
  urls:
    - https://${URL}
