########################################################
# bazarr
#
# Create password:
# htpasswd -c ~/traefik/auth/.lobechatpasswd arranhs
########################################################
services:
  lobechat:
    container_name: ${NAME}
    image: lobehub/lobe-chat:latest
    restart: unless-stopped
    networks:
      - traefik
    ports:
      - 3210:3210
    environment:
      - ACCESS_CODE=-
    labels:
      - traefik.enable=true
      - traefik.http.routers.${NAME}.rule=Host(`${URL}`)
      - traefik.http.routers.${NAME}.middlewares=oauth
networks:
  traefik:
    external: true
x-dockge:
  urls:
    - https://${URL}
