########################################################
# sftpgo
########################################################
services:
  sftpgo:
    container_name: ${NAME}
    image: drakkan/sftpgo:latest
    restart: unless-stopped
    networks:
      - traefik
    ports:
      - 8090:8080
      # - 2022:2022 # SFTP Port
      # - 10080:10080 # WebDav Port
    volumes:
      - ~:/ArranServer
      - ~/sftpgo:/var/lib/sftpgo
    environment:
      - SFTPGO_WEBDAVD__BINDINGS__0__PORT=10080
    labels:
      - traefik.enable=true
      - traefik.http.routers.${NAME}.rule=Host(`${URL}`)
      - traefik.http.routers.${NAME}.service=${NAME}
      - traefik.http.services.${NAME}.loadbalancer.server.port=8080
      # WebDav
      # - traefik.http.routers.${WEBDAV_NAME}.rule='Host(`${WEBDAV_URL}`)'
      # - traefik.http.routers.${WEBDAV_NAME}.service=${WEBDAV_NAME} \
      # - traefik.http.services.${WEBDAV_NAME}.loadbalancer.server.port=10080
networks:
  traefik:
    external: true
x-dockge:
  urls:
    - https://${URL}
