########################################################
# webdav
#
# Create password:
# htpasswd -c ~/traefik/auth/.webdavpasswd arranhs
########################################################
services:
  webdav:
    container_name: $NAME
    image: rclone/rclone:latest
    restart: unless-stopped
    networks:
      - traefik
    ports:
      - 8888:8888
    volumes:
      - ~:/files
    user: 1000:1000
    environment:
      - TZ=Europe/London
    labels:
      - traefik.enable=true
      - traefik.http.routers.$NAME.rule=Host(`$URL`)
      - traefik.http.routers.$NAME.middlewares=$NAME
      - traefik.http.middlewares.$NAME.basicAuth.usersfile=/auth/.${NAME}passwd
    command: |
      serve webdav /files
        -v
        --addr 0.0.0.0:8888
        --vfs-cache-mode off
networks:
  traefik:
    external: true
