########################################################
# traefik-forward-auth
########################################################
services:
  traefik-forward-auth:
    container_name: ${NAME}
    image: thomseddon/traefik-forward-auth:2
    networks:
      - traefik
    ports:
      - 4181:4181
    environment:
      - WHITELIST=ahobsonsayers@gmail.com
      - COOKIE_DOMAIN=arranhs.com
      - AUTH_HOST=${URL}
      - DEFAULT_PROVIDER=google
      - INSECURE_COOKIE=false
      - LOG_LEVEL=debug
      - LOG_FORMAT=pretty
    env_file:
      # Set in .env.secrets:
      # - SECRET
      # - PROVIDERS_GOOGLE_CLIENT_ID
      # - PROVIDERS_GOOGLE_CLIENT_SECRET
      - .env.secrets
    labels:
      - traefik.enable=true
      - traefik.http.routers.${NAME}.rule=Host(`${URL}`)
      - traefik.http.routers.${NAME}.middlewares=oauth
      - traefik.http.middlewares.oauth.forwardauth.address=http://traefik-forward-auth:4181
      - traefik.http.middlewares.oauth.forwardauth.authResponseHeaders=X-Forwarded-User
networks:
  traefik:
    external: true
x-dockge:
  urls:
    - https://${URL}
